#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v20
# autospec commit: a19cdc7
#
Name     : pypi-tables
Version  : 3.10.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/0d/5d/96708a84e9fcd29d1f684d56d4c38a23d29b1c934599a072a49f27ccfa71/tables-3.10.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/0d/5d/96708a84e9fcd29d1f684d56d4c38a23d29b1c934599a072a49f27ccfa71/tables-3.10.1.tar.gz
Summary  : Hierarchical datasets for Python
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: pypi-tables-bin = %{version}-%{release}
Requires: pypi-tables-license = %{version}-%{release}
Requires: pypi-tables-python = %{version}-%{release}
Requires: pypi-tables-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : c-blosc-dev
BuildRequires : c-blosc2-dev
BuildRequires : hdf5-dev
BuildRequires : lzo-dev
BuildRequires : pypi(blosc2)
BuildRequires : pypi(cython)
BuildRequires : pypi(msgpack)
BuildRequires : pypi(ndindex)
BuildRequires : pypi(numexpr)
BuildRequires : pypi(numpy)
BuildRequires : pypi(packaging)
BuildRequires : pypi(py_cpuinfo)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(typing_extensions)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
In these directories you can find some scripts contributed by PyTables
users. If you have any suggestion on them, please contact the original
authors.

%package bin
Summary: bin components for the pypi-tables package.
Group: Binaries
Requires: pypi-tables-license = %{version}-%{release}

%description bin
bin components for the pypi-tables package.


%package license
Summary: license components for the pypi-tables package.
Group: Default

%description license
license components for the pypi-tables package.


%package python
Summary: python components for the pypi-tables package.
Group: Default
Requires: pypi-tables-python3 = %{version}-%{release}

%description python
python components for the pypi-tables package.


%package python3
Summary: python3 components for the pypi-tables package.
Group: Default
Requires: python3-core
Provides: pypi(tables)
Requires: pypi(blosc2)
Requires: pypi(msgpack)
Requires: pypi(ndindex)
Requires: pypi(numexpr)
Requires: pypi(numpy)
Requires: pypi(packaging)
Requires: pypi(py_cpuinfo)
Requires: pypi(typing_extensions)

%description python3
python3 components for the pypi-tables package.


%prep
%setup -q -n tables-3.10.1
cd %{_builddir}/tables-3.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729496606
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-tables
cp %{_builddir}/tables-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-tables/f49fe28e8be059c0c4fa5d94ae8d8ca8d4f57292 || :
cp %{_builddir}/tables-%{version}/LICENSES/BLOSC.txt %{buildroot}/usr/share/package-licenses/pypi-tables/b44c80bba483ca60067ad08164da5852c189a6f4 || :
cp %{_builddir}/tables-%{version}/LICENSES/CLOUD-SPTHEME.txt %{buildroot}/usr/share/package-licenses/pypi-tables/801f15233c4e16ea9ce9b0579f6cd26f954c491b || :
cp %{_builddir}/tables-%{version}/LICENSES/FASTLZ.txt %{buildroot}/usr/share/package-licenses/pypi-tables/350f74b0e80aa38c5a75d8de5f367706920fdaa4 || :
cp %{_builddir}/tables-%{version}/LICENSES/H5PY.txt %{buildroot}/usr/share/package-licenses/pypi-tables/4632dda9973ee86bf5b9e03af0ad0cb22898e5a7 || :
cp %{_builddir}/tables-%{version}/LICENSES/SNAPPY.txt %{buildroot}/usr/share/package-licenses/pypi-tables/0d45aa696e5c82d8d1a1a1bbdc55d8e5fc328ccc || :
cp %{_builddir}/tables-%{version}/LICENSES/STDINT.txt %{buildroot}/usr/share/package-licenses/pypi-tables/8f81630ce8c11a4e5fe3ae090055425a933b85db || :
cp %{_builddir}/tables-%{version}/LICENSES/WIN32PTHREADS.txt %{buildroot}/usr/share/package-licenses/pypi-tables/f91db2685ced5f6d9dc81e4d6653550b31967fa9 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pt2to3
/usr/bin/ptdump
/usr/bin/ptrepack
/usr/bin/pttree

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-tables/0d45aa696e5c82d8d1a1a1bbdc55d8e5fc328ccc
/usr/share/package-licenses/pypi-tables/350f74b0e80aa38c5a75d8de5f367706920fdaa4
/usr/share/package-licenses/pypi-tables/4632dda9973ee86bf5b9e03af0ad0cb22898e5a7
/usr/share/package-licenses/pypi-tables/801f15233c4e16ea9ce9b0579f6cd26f954c491b
/usr/share/package-licenses/pypi-tables/8f81630ce8c11a4e5fe3ae090055425a933b85db
/usr/share/package-licenses/pypi-tables/b44c80bba483ca60067ad08164da5852c189a6f4
/usr/share/package-licenses/pypi-tables/f49fe28e8be059c0c4fa5d94ae8d8ca8d4f57292
/usr/share/package-licenses/pypi-tables/f91db2685ced5f6d9dc81e4d6653550b31967fa9

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
